import { lazy } from 'react'

export const AuthActions = lazy(() => import('components/Auth/Actions'))
export const AlertModal = lazy(() => import('components/Modals/Alert'))
export const AuthLogo = lazy(() => import('components/Auth/Logo'))
export const Banners = lazy(() => import('components/Home/Banners'))
export const BaseModal = lazy(() => import('components/Modals/Base'))
export const EmailAndPass = lazy(() => import('components/Auth/EmailAndPass'))
export const HomePitches = lazy(() => import('components/Pitches/home'))
export const Logout = lazy(() => import('components/Auth/Logout'))
export const Main = lazy(() => import('components/Main'))
export const ProfileImage = lazy(() => import('components/Profile/Image'))
export const ProfilePitches = lazy(() => import('components/Pitches/profile'))
export const PitchBadge = lazy(() => import('components/Pitch/Badge'))
export const PitchBanner = lazy(() => import('components/Pitch/Banner'))
export const PledgeModal = lazy(() => import('components/Modals/Pledge'))
export const PitchUser = lazy(() => import('components/Pitch/User'))
export const PitchActions = lazy(() => import('components/Pitch/Actions'))
export const PledgesAndComments = lazy(() => import('components/Pitch/PledgesAndComments'))
export const Searchbox = lazy(() => import('components/Searchbox'))
export const Slide = lazy(() => import('components/Home/Slide'))
